name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 14.x

      - name: Install dependencies
        run: yarn install

      - name: Compile
        run: yarn compile

      - name: Run tests
        run: yarn test && yarn test:size-contracts

      - name: Codecov
        run: |
          yarn install
          yarn run test:coverage
          bash <(curl -s https://codecov.io/bash) -t 095f2e4a-8a13-4e4f-8f29-32238b2aa8ee